# Uncomment the next line to define a global platform for your project
# platform :ios, '14.1'

target 'BusinessOrganization' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusinessOrganization

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Crashlytics'
pod 'Firebase/Performance'
pod 'Firebase/Analytics'

end
